package com.apps.talli;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DropMode;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

@SuppressWarnings("serial")
public class GuessingGame extends JFrame {
	
	private JTextField txtcin;
	private JTextArea txtrOutput;
	private JButton btnGuess;
	private int theNumber = 0;
	private int triesLeft = 7;
	
	public void newGame(){
		theNumber = (int)(Math.random()*100 + 1);
		triesLeft = 7;
		txtrOutput.setText("You have 7 tries to Guess the Random Number Generated by Computer! Let's Play!");
		txtcin.setText("");
	}
	
	public void checkGuess(){
		String guessText = txtcin.getText();
		String message = "";
		try {
					int guess = Integer.parseInt(guessText);
					triesLeft--;
					
					if (guess<theNumber && guess>0) {
							message = guess + " is Low! You have " + triesLeft + " tries left.";
							txtrOutput.setText(message);
						}
						else if(guess>theNumber && guess<101){
							message = guess + " is High! You have " + triesLeft + " tries left.";
							txtrOutput.setText(message);
						}
						else if(guess>100 || guess<1){
							triesLeft++;
							message = "Guess a Number between 1-100!! You have " + triesLeft + " tries left.";
							txtrOutput.setText(message);
						}
						else{
								int i = 7 - triesLeft;
								message = guess + " is the Number! You Won";
								txtrOutput.setText(message);
								int dialogResult = javax.swing.JOptionPane.showConfirmDialog(null, "You Win!!" + "Used "
								+  i  + " tries." + "\nPlay Again?", "Game Over", 0);
								if(dialogResult == 1){
									System.exit(0);
								}
								else{
									newGame();
								}
							}
					
					if(triesLeft<=0){
						message = guess + " is the Wrong Number! You have NO tries left.";
						txtrOutput.setText(message);
						int dialogResult = javax.swing.JOptionPane.showConfirmDialog(null, "You Loose!! The Number was " 
						+ theNumber + ". Play Again?", "Game Over", 0);
						if(dialogResult == 1){
							System.exit(0);
						}else{
						newGame();
						}
					}
					
			} catch (Exception e) {
			message = "Error!!!\nYou have " + triesLeft + " tries left.";
			txtrOutput.setText(message);
			

		} finally{
				
				txtcin.requestFocus();
				txtcin.selectAll();
		}
	}
		
		
	public GuessingGame() {
		setTitle("High Low Game");
		setResizable(false);
		setOpacity(1.0f);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBackground(Color.RED);
		getContentPane().setForeground(Color.GREEN);
		getContentPane().setFont(new Font("Consolas", Font.PLAIN, 11));
		getContentPane().setBackground(new Color(51, 51, 51));
		getContentPane().setLayout(null);
		
		JLabel lblVimanyusGuessingGame = new JLabel("Vimanyu's Guessing Game");
		lblVimanyusGuessingGame.setToolTipText("Try and Guess the Random Number Genreated by the Computer in 7 Attempts!! HAVE FUN!!");
		lblVimanyusGuessingGame.setBounds(47, 11, 339, 27);
		lblVimanyusGuessingGame.setFont(new Font("Consolas", Font.BOLD, 22));
		lblVimanyusGuessingGame.setBackground(new Color(255, 0, 51));
		lblVimanyusGuessingGame.setForeground(new Color(51, 51, 51));
		lblVimanyusGuessingGame.setOpaque(true);
		lblVimanyusGuessingGame.repaint();
		lblVimanyusGuessingGame.setHorizontalAlignment(SwingConstants.CENTER);
		lblVimanyusGuessingGame.setVerticalAlignment(SwingConstants.TOP);
		getContentPane().add(lblVimanyusGuessingGame);
		
		JLabel lblGuessANumber = new JLabel("ENTER A NUMBER BETWEEN 1 TO 100");
		lblGuessANumber.setBounds(63, 49, 307, 14);
		lblGuessANumber.setFont(new Font("Consolas", Font.BOLD, 16));
		lblGuessANumber.setBackground(new Color(0, 153, 204));
		lblGuessANumber.setForeground(new Color(255, 0, 51));
		lblGuessANumber.repaint();
		lblGuessANumber.setHorizontalAlignment(SwingConstants.CENTER);
		lblGuessANumber.setVerticalAlignment(SwingConstants.TOP);
		getContentPane().add(lblGuessANumber);
		
		txtcin = new JTextField();
		txtcin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {	
				checkGuess();
			}
		});
		txtcin.setToolTipText("Enter Number Here!");
		txtcin.setHorizontalAlignment(SwingConstants.CENTER);
		txtcin.setForeground(Color.ORANGE);
		txtcin.setDropMode(DropMode.INSERT);
		txtcin.setBackground(new Color(255, 0, 51));
		txtcin.setFont(new Font("Comic Sans MS", Font.BOLD, 74));
		txtcin.setBounds(147, 74, 139, 122);
		getContentPane().add(txtcin);
		txtcin.setColumns(10);
		
		JSeparator separator = new JSeparator();
		separator.setForeground(new Color(255, 0, 51));
		separator.setBackground(new Color(51, 51, 51));
		separator.setBounds(10, 261, 414, 14);
		getContentPane().add(separator);
		
		JLabel lblAppCreatedBy = new JLabel("App Created By Vimanyu Aggarwal");
		lblAppCreatedBy.setToolTipText("Contact Me - 8860014725");
		lblAppCreatedBy.setBackground(new Color(255, 0, 51));
		lblAppCreatedBy.setForeground(new Color(51, 51, 51));
		lblAppCreatedBy.setFont(new Font("Consolas", Font.BOLD, 14));
		lblAppCreatedBy.setOpaque(true);
		lblAppCreatedBy.setHorizontalAlignment(SwingConstants.CENTER);
		lblAppCreatedBy.setBounds(0, 407, 450, 14);
		getContentPane().add(lblAppCreatedBy);
		
		btnGuess = new JButton("Guess!");
		btnGuess.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				checkGuess();
			}
		});
		btnGuess.setToolTipText("Guess the Number!");
		btnGuess.setSelectedIcon(new ImageIcon("X:\\Vimanyu\\Dux-Flat-Button-iconSET (1)\\06 click.png"));
		btnGuess.setIcon(new ImageIcon("X:\\Vimanyu\\Dux-Flat-Button-iconSET (1)\\06 normal.png"));
		btnGuess.setBounds(135, 207, 162, 43);
		getContentPane().add(btnGuess);
		
		txtrOutput = new JTextArea();
		txtrOutput.setEditable(false);
		txtrOutput.setWrapStyleWord(true);
		txtrOutput.setLineWrap(true);
		txtrOutput.setFont(new Font("Consolas", Font.BOLD, 22));
		txtrOutput.setForeground(new Color(255, 0, 51));
		txtrOutput.setBackground(new Color(51, 51, 51));
		txtrOutput.setText("You have 7 tries to Guess the Random Number Generated by Computer! Let's Play!");
		txtrOutput.setBounds(23, 286, 387, 100);
		getContentPane().add(txtrOutput);
	}

	public static void main(String[] args) {
		GuessingGame theGame = new GuessingGame();
		theGame.newGame();
		theGame.setSize(new Dimension(450, 450));
		theGame.setVisible(true);
	}
}
